apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hw451to48-go
  janus-idp.io/tekton: hw451to48-go
  backstage.io/kubernetes-id: hw451to48-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hw451to48-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
