apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hw451to48-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hw451to48-go 
  name: hw451to48-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hw451to48-go 
